; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.13"

projects[views_oai_pmh][subdir] = "contrib"
projects[views_oai_pmh][version] = "1.2"

