; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.9"

projects[date][subdir] = "contrib"
projects[date][version] = "2.9"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.10"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-beta2"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.1"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.5"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[views][subdir] = "contrib"
projects[views][version] = "3.13"

projects[views_oai_pmh][subdir] = "contrib"
projects[views_oai_pmh][version] = "1.2"

; Themes
projects[zen][version] = "6.4"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nvli_audio_video][download][type] = ""
projects[nvli_audio_video][download][url] = ""
projects[nvli_audio_video][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[nvli_field_bases][download][type] = ""
projects[nvli_field_bases][download][url] = ""
projects[nvli_field_bases][type] = "module"

