<?php
/**
 * @file
 * nvli_newspaper.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function nvli_newspaper_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => "1");
  }
  if ($module == "feeds_tamper" && $api == "feeds_tamper_default") {
    return array("version" => "2");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function nvli_newspaper_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function nvli_newspaper_node_info() {
  $items = array(
    'newspaper' => array(
      'name' => t('Newspaper'),
      'base' => 'node_content',
      'description' => t('Entity to store Newspaper data'),
      'has_title' => '1',
      'title_label' => t('News Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
